//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaitanetDinar421.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patrinymic { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public Nullable<int> IdRole { get; set; }
        public byte[] ImageBytes { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
